# fly.toml app configuration file generated for muddy-sea-3151 on 2023-05-16T22:47:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "muddy-sea-3151"
primary_region = "jnb"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  http_checks = []
  processes = ["app"]
